name: Vert.x - HTTP & Config Map
description: Simple HTTP endpoint where the Vert.x application uses OpenShift ConfigMap to get the application parameters.
source:
  git:
    url: https://github.com/openshiftio-vertx-boosters/vertx-configmap-booster-redhat
    ref: master
environment:
  staging:
    source:
      git:
        ref: v14
  production:
    source:
      git:
        ref: v14
